### PR TITLE
Detect if emuiibo is loaded to evoid black screen

### PR DESCRIPTION
**Pull request by Kronos2308**
added gitignore
detect emuiibo service to evoid blak screen

### CODE REVIEW

**Comment by CompSciOrBust** [comment]
I'm a bit busy at the minute so I'll merge it later once I've had a proper look. This is great, thanks. When I tried to add it myself nfp ipc just froze if Emuiibo wasn't running. One small thing I noticed at a glance is that you set the footer red. Could you change that to be purple? (255, 0 , 255). I want every status to have a different color.

**Review by CompSciOrBust — APPROVED** [review]
Seems to work fine

**Comment by Kronos2308** [comment]
@CompSciOrBust 
ok I'll put it purple
,
One thing I have noticed is the little difference between the color of
the list and the one of the buttons
Won't something like that be better?

Screenshoot1

ScreenShoot2

**Comment by CompSciOrBust** [comment]
Oh actually I've just did a git commit making it purple haha. Yeah you're right. I think it would be better if the selected item was white and the rest were blue though. I don't like the inactive list being gray. I played around with it but never got it to look quite right imo.

Edit: If you do a pr changing the selected item to be white and the rest to be blue (so the inverse of what you have now) and make the inactive list the same blue instead of gray I'll merge that.

**Comment by Kronos2308** [comment]
XD ok maybe gray looks ugly
but there should be a difference when you are on the list or when you touch the buttons it helps to orient yourself in the app

nfpemu.c
is using deprecated elements and will disappear in the next update of the libnx

**Comment by CompSciOrBust** [comment]
Imo it's alright because the user can see which list is selected from the highlighted option. If you can find a colour that looks nice I'll merge it though.

nfpemu.c and nfpemu.h comes from XorTroll's Emuiibo repo. I think he'll probably rewrite it in the next emuiibo update. https://github.com/XorTroll/emuiibo#for-developers

Edit: I just added you to the credits in the read me file too

**Comment by Kronos2308** [comment]
@CompSciOrBust 
https://github.com/XorTroll/emuiibo#for-developers
true , in that case I shouldn't have touched nfpemu.c code
https://github.com/StarDustCFW/Amiigo/commit/bc5e750e50fae126bb23e7d00f6bf5110417c17d

**Comment by Kronos2308** [comment]
it's better this way?

2020012116244100-DB1426D1DFD034027CECDE9C2DD914B8
2020012116244400-DB1426D1DFD034027CECDE9C2DD914B8

**Comment by CompSciOrBust** [comment]
Oh no it's fine. I think the nfp ipc was broken anyway which is why when I tried to detect if Emuiibo was working it would freeze. That colour scheme works fine. I'm not sure how it works now that I've already merged your other pr. Do you need to do another pr or is there a way to do it from this thread?

Edit: You should probably do a pr on Emuiibo with your edits for other people who use it.

**Pull request merged**
